<a href="https://colab.research.google.com/github/erica00j/machinelearning/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import preprocessing

data_set = pd.read_excel('/content/Data_Feature_Scaling.xlsx')
data_set.head()

Country  Age  Salary  Purchased
0  France   44   72000          0
1   Spain   27   48000          1
2     USA   30   54000          0
3   Spain   38   61000          0
4     USA   40    1000          1

In [3]:
#here Features - Age and Salary columns
#are taken using slicing
#to handle values with varying magnitude
x = data_set.iloc[:,1:3].values
print("\nOriginal data values : \n",x)


Original data values : 
 [[   44 72000]
 [   27 48000]
 [   30 54000]
 [   38 61000]
 [   40  1000]
 [   35 58000]
 [   78 52000]
 [   48 79000]
 [   50 83000]
 [   37 67000]]


:은 모든 행, 1:3은 1,2열

In [4]:
""" MIN MAX SCALER """
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))

#Scaled feature
min_max_scaler.fit(x)
x_after_min_max_scaler = min_max_scaler.transform(x)

print ("\nAfter min max Scaling : \n",x_after_min_max_scaler)

""" Standardisation """
Standardisation = preprocessing.StandardScaler()

#Scaled feature
Standardisation.fit(x)
x_after_Standardisation = Standardisation.transform(x)

print ("\nAfter Standardisation : \n",x_after_Standardisation)



After min max Scaling : 
 [[0.33333333 0.86585366]
 [0.         0.57317073]
 [0.05882353 0.64634146]
 [0.21568627 0.73170732]
 [0.25490196 0.        ]
 [0.15686275 0.69512195]
 [1.         0.62195122]
 [0.41176471 0.95121951]
 [0.45098039 1.        ]
 [0.19607843 0.80487805]]

After Standardisation : 
 [[ 0.09536935  0.66527061]
 [-1.15176827 -0.43586695]
 [-0.93168516 -0.16058256]
 [-0.34479687  0.16058256]
 [-0.1980748  -2.59226136]
 [-0.56487998  0.02294037]
 [ 2.58964459 -0.25234403]
 [ 0.38881349  0.98643574]
 [ 0.53553557  1.16995867]
 [-0.41815791  0.43586695]]


standard scaler는 Xnew = (Xi-Xmean)/s.d(1)
MinMax Scaler는 Xnew = (Xi-min(X))/(max(X)-min(X))
만약 7번째면 (78-27)/(78-27)=1
After min max Scaling은 0~1사이의 값
